server:
  # jetty  undertow
  undertow:
    # 设置IO线程数,它主要执行非阻塞的任务, 它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 8
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 120
    # 以下的配置会影响buffer, 这些buffer会用于服务器连接的IO操作, 有点类似netty的池化内存管理, 每块buffer的空间大小, 越小的空间被利用越充分
    buffer-size: 2048
    # 是否分配的直接内存
    direct-buffers: true

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      # Max file size, 默认1M
      max-file-size: 512MB
      # Max request size, 默认10M
      max-request-size: 512MB

dozer:
  mappingFiles:
    - classpath:dozer/global.dozer.xml
    - classpath:dozer/biz.dozer.xml

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    # feign 熔断机制是否开启
    enabled: true
  # 支持压缩的mime types
  # 请求压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    # 响应压缩
    response:
      enabled: true

ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  eureka:
    enabled: true
  ReadTimeout: 30000
  # [ribbon超时时间]大于[熔断超时], 那么会先走熔断, 相当于你配的ribbon超时就不生效了
  # ribbon和hystrix是同时生效的, 哪个值小哪个生效
  ConnectTimeout: 30000
  # 最大自动重试
  MaxAutoRetries: 0
  # 最大自动像下一个服务重试
  MaxAutoRetriesNextServer: 1
  # 无论是请求超时或者socket read timeout都进行重试
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      # 并发执行的最大线程数, 默认10
      coreSize: 1000
      # BlockingQueue的最大队列数
      maxQueueSize: 1000
      # 即使maxQueueSize没有达到, 达到queueSizeRejectionThreshold该值后, 请求也会被拒绝
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时 ribbon和hystrix是同时生效的, 哪个值小哪个生效
            timeoutInMilliseconds: 120000

id-generator:
  # id生成器机器掩码
  machine-code: 1
